import type { Metadata } from 'next'
import { Jost } from 'next/font/google'

import { cn } from '@/lib/utils'

import './main.css'

const JostFont = Jost({
  variable: '--font-jost',
  subsets: ['latin', 'cyrillic'],
  style: ['normal', 'italic'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(JostFont.variable, 'antialiased')}>{children}</body>
    </html>
  )
}
